2025-03-13 13:54:25,816	INFO worker.py:1841 -- Started a local Ray instance.
[36m(PoolActor pid=12142)[0m *** SIGSEGV received at time=1741888506 on cpu 123 ***
[36m(PoolActor pid=12142)[0m PC: @     0x14a8a880bcfe  (unknown)  ray::gcs::TaskInfoAccessor::AsyncAddTaskEventData()
[36m(PoolActor pid=12142)[0m     @     0x14a8b748ad10       1792  (unknown)
[36m(PoolActor pid=12142)[0m     @     0x14a8a86eea45       1392  ray::core::worker::TaskEventBufferImpl::FlushEvents()
[36m(PoolActor pid=12142)[0m     @     0x14a8a867aa0c       1488  ray::core::CoreWorker::Disconnect()
[36m(PoolActor pid=12142)[0m     @     0x14a8a867adbd       1152  ray::core::CoreWorker::ForceExit()
[36m(PoolActor pid=12142)[0m     @     0x14a8a867b1ef       1680  ray::core::CoreWorker::HandleKillActor()
[36m(PoolActor pid=12142)[0m     @     0x14a8a86726f4        192  ray::rpc::ServerCallImpl<>::HandleRequestImpl()
[36m(PoolActor pid=12142)[0m     @     0x14a8a89c1128       1168  EventTracker::RecordExecution()
[36m(PoolActor pid=12142)[0m     @     0x14a8a89bc0fe         48  std::_Function_handler<>::_M_invoke()
[36m(PoolActor pid=12142)[0m     @     0x14a8a89bc576        112  boost::asio::detail::completion_handler<>::do_complete()
[36m(PoolActor pid=12142)[0m     @     0x14a8a8f91cbb        128  boost::asio::detail::scheduler::do_run_one()
[36m(PoolActor pid=12142)[0m     @     0x14a8a8f93639        288  boost::asio::detail::scheduler::run()
[36m(PoolActor pid=12142)[0m     @     0x14a8a8f93d42         96  boost::asio::io_context::run()
[36m(PoolActor pid=12142)[0m     @     0x14a8a85b7b81       1280  ray::core::CoreWorker::RunIOService()
[36m(PoolActor pid=12142)[0m     @     0x14a8a8a72890         64  thread_proxy
[36m(PoolActor pid=12142)[0m     @     0x14a8b74801ca  (unknown)  start_thread
[36m(PoolActor pid=12142)[0m [2025-03-13 13:55:06,606 E 12142 12175] logging.cc:460: *** SIGSEGV received at time=1741888506 on cpu 123 ***
[36m(PoolActor pid=12142)[0m [2025-03-13 13:55:06,606 E 12142 12175] logging.cc:460: PC: @     0x14a8a880bcfe  (unknown)  ray::gcs::TaskInfoAccessor::AsyncAddTaskEventData()
[36m(PoolActor pid=12142)[0m [2025-03-13 13:55:06,606 E 12142 12175] logging.cc:460:     @     0x14a8b748ad10       1792  (unknown)
[36m(PoolActor pid=12142)[0m [2025-03-13 13:55:06,606 E 12142 12175] logging.cc:460:     @     0x14a8a86eea45       1392  ray::core::worker::TaskEventBufferImpl::FlushEvents()
[36m(PoolActor pid=12142)[0m [2025-03-13 13:55:06,606 E 12142 12175] logging.cc:460:     @     0x14a8a867aa0c       1488  ray::core::CoreWorker::Disconnect()
[36m(PoolActor pid=12142)[0m [2025-03-13 13:55:06,606 E 12142 12175] logging.cc:460:     @     0x14a8a867adbd       1152  ray::core::CoreWorker::ForceExit()
[36m(PoolActor pid=12142)[0m [2025-03-13 13:55:06,606 E 12142 12175] logging.cc:460:     @     0x14a8a867b1ef       1680  ray::core::CoreWorker::HandleKillActor()
[36m(PoolActor pid=12142)[0m [2025-03-13 13:55:06,606 E 12142 12175] logging.cc:460:     @     0x14a8a86726f4        192  ray::rpc::ServerCallImpl<>::HandleRequestImpl()
[36m(PoolActor pid=12142)[0m [2025-03-13 13:55:06,606 E 12142 12175] logging.cc:460:     @     0x14a8a89c1128       1168  EventTracker::RecordExecution()
[36m(PoolActor pid=12142)[0m [2025-03-13 13:55:06,606 E 12142 12175] logging.cc:460:     @     0x14a8a89bc0fe         48  std::_Function_handler<>::_M_invoke()
[36m(PoolActor pid=12142)[0m [2025-03-13 13:55:06,606 E 12142 12175] logging.cc:460:     @     0x14a8a89bc576        112  boost::asio::detail::completion_handler<>::do_complete()
[36m(PoolActor pid=12142)[0m [2025-03-13 13:55:06,606 E 12142 12175] logging.cc:460:     @     0x14a8a8f91cbb        128  boost::asio::detail::scheduler::do_run_one()
[36m(PoolActor pid=12142)[0m [2025-03-13 13:55:06,606 E 12142 12175] logging.cc:460:     @     0x14a8a8f93639        288  boost::asio::detail::scheduler::run()
[36m(PoolActor pid=12142)[0m [2025-03-13 13:55:06,606 E 12142 12175] logging.cc:460:     @     0x14a8a8f93d42         96  boost::asio::io_context::run()
[36m(PoolActor pid=12142)[0m [2025-03-13 13:55:06,606 E 12142 12175] logging.cc:460:     @     0x14a8a85b7b81       1280  ray::core::CoreWorker::RunIOService()
[36m(PoolActor pid=12142)[0m [2025-03-13 13:55:06,606 E 12142 12175] logging.cc:460:     @     0x14a8a8a72890         64  thread_proxy
[36m(PoolActor pid=12142)[0m [2025-03-13 13:55:06,606 E 12142 12175] logging.cc:460:     @     0x14a8b74801ca  (unknown)  start_thread
[36m(PoolActor pid=12142)[0m Fatal Python error: Segmentation fault
[36m(PoolActor pid=12142)[0m 
[36m(PoolActor pid=12142)[0m 
[36m(PoolActor pid=12142)[0m Extension modules: msgpack._cmsgpack, google._upb._message, psutil._psutil_linux, psutil._psutil_posix, setproctitle, yaml._yaml, _cffi_backend, ray._raylet, pvectorc, mkl._mklinit, mkl._py_mkl_service, numpy.core._multiarray_umath, numpy.core._multiarray_tests, numpy.linalg.lapack_lite, numpy.linalg._umath_linalg, numpy.fft._pocketfft_internal, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator (total: 25)
Map: random_32_32_10 requires 2 runs
Map: warehouse_10_20_10_2_2 requires 4 runs
[36m(checkIfRunNextAgents pid=11955)[0m Completed map: random_32_32_10, agentNum: 50, combined_df: (2, 44)
[36m(checkIfRunNextAgents pid=11955)[0m 2 2 50 random_32_32_10
[36m(checkIfRunNextAgents pid=11899)[0m 2 2 100 random_32_32_10
[36m(checkIfRunNextAgents pid=11899)[0m Finished all agent numbers for map: random_32_32_10
[36m(checkIfRunNextAgents pid=11899)[0m 4 4 50 warehouse_10_20_10_2_2
------------ Finished eecbs Calls in :16.335 seconds
[36m(checkIfRunNextAgents pid=11899)[0m 4 4 100 warehouse_10_20_10_2_2
[36m(checkIfRunNextAgents pid=11899)[0m Finished all agent numbers for map: warehouse_10_20_10_2_2
------------ Finished Data Manipulator in :36.226 seconds
[36m(checkIfRunNextAgents pid=11899)[0m Completed map: warehouse_10_20_10_2_2, agentNum: 100, combined_df: (8, 44)[32m [repeated 3x across cluster] (Ray deduplicates logs by default. Set RAY_DEDUP_LOGS=0 to disable log deduplication, or see https://docs.ray.io/en/master/ray-observability/user-guides/configure-logging.html#log-deduplication for more options.)[0m
2025-03-13 13:55:11,872	INFO worker.py:1841 -- Started a local Ray instance.
Map: random_32_32_10 requires 2 runs
Map: warehouse_10_20_10_2_2 requires 4 runs
[36m(checkIfRunNextAgents pid=13226)[0m Finished all scens for map: random_32_32_10
------------ Finished eecbs Calls in :30.701 seconds
[36m(checkIfRunNextAgents pid=13288)[0m Finished all scens for map: warehouse_10_20_10_2_2
------------ Finished Data Manipulator in :9.303 seconds
